### ISSUE TITLE
save state?

### ISSUE THREAD

**Issue by valdr** [raandoom/qml2048#8]
Is there a possibility to save the state of a board, so that when you want to *check* the settings or the app crashes/is closed, the board isn't actually lost?

Especially for checking settings, losing one's game is rather annoying.

**Comment by raandoom** [comment]
You are asking for Save button. Am I right? It is easy, trying to do add ASAP.
What do you mean with 'check'? You are talking about something like Load button?

**Comment by valdr** [comment]
At the moment, when I am in a game and I just want to doublecheck the settings (don't know why...), when I come back, I get a new board.
So yes, a save/load button ór autosave is what I am wondering about.

**Comment by raandoom** [comment]
At first: do we talking about my Harmattan version of qml2048 or about Sailfish fork of it? I saw that you forks Sailfish fork from condo4.

**Comment by valdr** [comment]
I am mainly talking about the Sailfish version.
I noticed that condo4 forked before you added saving of states, or what seems to be saving of the state...

**Comment by raandoom** [comment]
I think that better if you open this issue at Sailfish fork repository, because I cant give you the right answer about Sailfish version. You must ask condo4.
Only I can tell to you, that for me autosave on exit game and autoload on open game works perfect. And again: I am talking about Harmattan version.
I am closing the issue, because in fact there is no issue here :)
